### ISSUE TITLE
Npm run dev package error

### ISSUE THREAD

**Issue by djengineer** [ansonla3/consensysProject#1]
I'm getting this error with npm run dev.

Is nuxt an important  part of your project?
```
> nuxt-web3-boilerplate@1.0.0 dev /home/orange/Desktop/eval
> nuxt

/home/orange/Desktop/eval/node_modules/nuxt/lib/core/middleware/nuxt.js:72
      const policies = this.options.render.csp.policies ? {...this.options.render.csp.policies} : null
                                                           ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/orange/Desktop/eval/node_modules/nuxt/lib/core/renderer.js:19:24)

```

**Comment by djengineer** [comment]
oops. sorry i changed to node version to latest node version
It runs!
